name: Build

env:
  GOPATH: /home/runner/work/go

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir -p $GOPATH/bin
        export PATH=$PATH:$GOPATH/bin
        make tools all

    
