name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v8
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.21', 'oldstable', 'stable' ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: |
        mkdir -p $GOPATH/bin
        export PATH=$PATH:$GOPATH/bin
        make test
